### ISSUE TITLE
Mod not loading

### ISSUE THREAD

**Issue by alcar2364** [89pleasure/cities2-extended-tooltip#1]
Hi! so mod is not loading for me. I have BepInEx 5 installed. Installed the Bepinex 5 version of this mod into the plugins folder. 4 Other plugins are loading (MOOB, Traffic Lights Enhancement, Unlock All Tiles, and Legacy Flavour). This mod isn't even listed as attempting to load.  I have attached a screenshot of the log.
![bepinex](https://github.com/89pleasure/cities2-extended-tooltip/assets/42076068/38dca5c9-b511-4911-8c8a-49a037154ca8)

**Comment by 89pleasure** [comment]
Hey thanks for reporting! 
Could you tell me how you use the mod?

First, Where did you download it?

**Comment by alcar2364** [comment]
From here (GitHub)

**Comment by 89pleasure** [comment]
Is fixed now. Thx for reporting :)
