### ISSUE TITLE
Game won't start with latest version installed manually.

### ISSUE THREAD

**Issue by orangecroc** [89pleasure/cities2-extended-tooltip#10]
My game wouldn't start with the new version. I did troubleshooting steps of removing all mods and adding them one at a time. This is the only mod that prevented the game from reaching the start screen.

**Comment by 89pleasure** [comment]
Did you forget to add HookUI too? This mod only works with HookUI as it is a requirement. It's in the readme.

**Comment by orangecroc** [comment]
Problem solved, I must have forgotten to add it back, thank you.
