### ISSUE TITLE
Expand unemployment rate into education levels

### ISSUE THREAD

**Issue by haritos90** [89pleasure/cities2-extended-tooltip#19]
Hello there! Is it possible to expand the unemployment rate (available in the population infoview) to education levels with this mod?

**Comment by haritos90** [comment]
I was thinking of the Population infoview - there is unemployment rate available. But I realise that it is not a tooltip change, so I'll check other mods! Thanks for the reply!

**Comment by 89pleasure** [comment]
you ever tried using Infixo's Info_Loom mod? Maybe that helps you.
