### ISSUE TITLE
request:  NA / EU level  mix use 

### ISSUE THREAD

**Issue by binded-zz** [89pleasure/cities2-extended-tooltip#2]
na /eu  and low med  hi low income  and then next line the address its very very hard with the small icons to really tell whats what
i love this mod already

**Comment by 89pleasure** [comment]
Could u explain a bit more what you mean with NA/EU level mix?

**Comment by binded-zz** [comment]
as in like this 
![theme NA](https://github.com/89pleasure/cities2-extended-tooltip/assets/458540/77743486-9179-460a-ba49-27fd6c33c0b6)
 theme 
NA = North American
EU = European Union


some thing like this but for housing
![basketball](https://github.com/89pleasure/cities2-extended-tooltip/assets/458540/e030b902-1b55-420d-bf3d-70a2e4d1de0a)

where its the icon then what it is 

![NA med dens](https://github.com/89pleasure/cities2-extended-tooltip/assets/458540/ed720bfc-f29d-4ad2-b3d0-22ee847c97c8)

so it would be like icon what the asset is like with the basketball  or skatepark 
then the address 

so like na low dens, na low dens row, na med dens, na med mix use, na meds dens low income , na high dens

then same with eu

**Comment by 89pleasure** [comment]
You mean next to the icon you would like to have the theme name too?
Like:
**[Icon][Theme][Density][Address]**

**Comment by binded-zz** [comment]
yes please that would be awsome

**Comment by 89pleasure** [comment]
Added with the newest update
