### ISSUE TITLE
The storage amount of warehouses shows 'Unknown' 

### ISSUE THREAD

**Issue by GIS-PuppetMaster** [89pleasure/cities2-extended-tooltip#20]
Game Version 1.0.18f1
mod Version V1.1.0
Game Language: Simplified Chinese

**Comment by 89pleasure** [comment]
Hey there! Thanks for the report! That's due to some missing translations for simplified chinese. 
Already working on updating the translations. I think I can fix that with the next update.

**Comment by GIS-PuppetMaster** [comment]
> Hey there! Thanks for the report! That's due to some missing translations for simplified chinese.嘿！感谢您的报告！这是由于缺少一些简体中文的翻译。 And should be fixed in V1.2.0. You're on an older version of the mod. Please update and see if this is fixed.并且应该在V1.2.0中修复。您使用的是旧版本的模组。请更新并查看此问题是否已修复。
> 
> https://thunderstore.io/c/cities-skylines-ii/p/Cities2Modding/ExtendedTooltip/
> 
> Github compiled version is not always up to dateGithub编译版本并不总是最新的

Thank you, it's fixed!

**Comment by GIS-PuppetMaster** [comment]
Thank you, it's fixed!

**Comment by GIS-PuppetMaster** [comment]
> Hey there! Thanks for the report! That's due to some missing translations for simplified chinese.嘿！感谢您的报告！这是由于缺少一些简体中文的翻译。 And should be fixed in V1.2.0. You're on an older version of the mod. Please update and see if this is fixed.并且应该在V1.2.0中修复。您使用的是旧版本的模组。请更新并查看此问题是否已修复。
> 
> https://thunderstore.io/c/cities-skylines-ii/p/Cities2Modding/ExtendedTooltip/
> 
> Github compiled version is not always up to dateGithub编译版本并不总是最新的

Thank you, it's fixed!
