### ISSUE TITLE
Add support for CS:II and PDX mods

### ISSUE THREAD

**Issue by brendeni1** [89pleasure/cities2-extended-tooltip#26]
I understand that this mod relies on HookUI, however, I'm wondering if it's possible to integrate this directly into PDX mods? Thanks!

**Comment by 89pleasure** [comment]
This mod does rely on Goose and not on HookUI. As long Gooee is not available on PDX mod it does not arrive there. 
You can still use both, Thundestore mods and PDX mods.

**Comment by brendeni1** [comment]
My bad, I must've mixed up another mod. Thanks for letting me know!
