### ISSUE TITLE
Release mod on Paradox Mods

### ISSUE THREAD

**Issue by PKizzle** [89pleasure/cities2-extended-tooltip#27]
@89pleasure Are you planning to publish the mod on Paradox Mods as well?

**Comment by Me1onSeed** [comment]
Please go on PDX. We really need it. T_T

**Comment by 89pleasure** [comment]
Will need some more time. Also a requirement mod (Gooee) is not yet on PDXMod. 
But, you can already use it. There is no issue combining Thunderstore mods with PDXMods.

**Comment by 89pleasure** [comment]
Done
