### ISSUE TITLE
Currency is displayed as Euro (€) instead of Cell (₡)

### ISSUE THREAD

**Issue by eiWare** [89pleasure/cities2-extended-tooltip#4]
Problem:
The ingame currency in the advanced tooltips is displayed as Euro (€)

Expected behavior:
The ingame currency should be displayed as Cells (₡) as that is the official currency in CS2

Screenshot:
![Untitled](https://github.com/89pleasure/cities2-extended-tooltip/assets/38304804/f6b70084-53a6-420c-a3a4-c3e875531644)

**Comment by 89pleasure** [comment]
hey there! Thanks for reporting. I know about this tiny mistake there. I already prepare a new release where this is going to be fixed.

**Comment by 89pleasure** [comment]
Fixed with the latest release :)
