### ISSUE TITLE
CS2 Crashing at startup of the game

### ISSUE THREAD

**Issue by NOOBERIST** [89pleasure/cities2-extended-tooltip#9]
My CS2 is crashing after the update whenever I try to start it. This mod is the only one that does this. I also tried this mod without other mods in the plugins folder. I'm playing on gamepass.

**Comment by 89pleasure** [comment]
hey there, please provide the log files from BepInEx folder of your game. Otherwise it's hard for me to tell whats causing your crashes.

**Comment by qualiall** [comment]
Same thing.  here is log file 
`Message:   BepInEx] BepInEx 5.4.22.0 - Cities2 (10/24/2023 1:13:51 PM)
[Info   :   BepInEx] Running under Unity v2022.3.7.9732149
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 7 plugins to load
[Info   :   BepInEx] Loading [C2VM.CommonLibraries.LaneSystem 0.0.3]
[Info   :C2VM.CommonLibraries.LaneSystem] Plugin C2VM.CommonLibraries.LaneSystem 0.0.3 is loaded!
[Info   :   BepInEx] Loading [C2VM.TrafficLightsEnhancement 0.2.3]
[Info   :C2VM.TrafficLightsEnhancement] Plugin C2VM.TrafficLightsEnhancement 0.2.3 is loaded!
[Info   :   Console] Logs at C:/Users/quali/AppData/LocalLow/Colossal Order/Cities Skylines II/Logs
[Info   :   BepInEx] Loading [Unified Icon Library 1.0.3]
[Info   :   BepInEx] Loading [ExtendedRoadUpgrades 1.3.2]
[Info   :ExtendedRoadUpgrades] Plugin ExtendedRoadUpgrades is loaded!
[Info   :ExtendedRoadUpgrades] Plugin ExtendedRoadUpgrades made patches! Patched methods: 4
[Info   :ExtendedRoadUpgrades] Patched method: Game.dll:Initialize
[Info   :ExtendedRoadUpgrades] Patched method: Game.dll:InitializeThumbnails
[Info   :ExtendedRoadUpgrades] Patched method: Colossal.IO.AssetDatabase.dll:.ctor
[Info   :ExtendedRoadUpgrades] Patched method: Game.dll:InitializeRaycast
[Info   :   BepInEx] Loading [ExtendedTooltip 0.7.0]
[Warning:  HarmonyX] AccessTools.GetTypesFromAssembly: assembly ExtendedTooltip, Version=0.7.0.0, Culture=neutral, PublicKeyToken=null => System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load file or assembly 'HookUILib, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <b89873cb176e44a995a4781c7487d410>:0 
  at HarmonyLib.AccessTools.GetTypesFromAssembly (System.Reflection.Assembly assembly) [0x0000d] in <474744d65d8e460fa08cd5fd82b5d65f>:0 
System.IO.FileNotFoundException: Could not load file or assembly 'HookUILib, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'HookUILib, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'
[Info   :ExtendedTooltip] Plugin ExtendedTooltip is loaded! Patched methods 4
[Info   :ExtendedTooltip] Patched method: Game.dll:Initialize
[Info   :ExtendedTooltip] Patched method: Colossal.Localization.dll:SetActiveLocale
[Info   :ExtendedTooltip] Patched method: Game.dll:OnCreate
[Info   :ExtendedTooltip] Patched method: Game.dll:OnUpdate
[Info   :   BepInEx] Loading [Unlock All Tiles Mod 1.0.0]
[Info   :Unlock All Tiles Mod] Plugin UnlockAllTilesMod 1.0.0 is loaded! Patched methods: 2
[Info   :Unlock All Tiles Mod] Patched method: Game.dll:get_cost
[Info   :Unlock All Tiles Mod] Patched method: Game.dll:GetAvailableTiles
[Info   :   BepInEx] Loading [SchoolCapacityBalancer 0.0.1]
[Info   :SchoolCapacityBalancer] Plugin SchoolCapacityBalancer 0.0.1 is loaded! Patched methods: 1
[Info   :SchoolCapacityBalancer] Patched method: Game.dll:AddPrefab
[Message:   BepInEx] Chainloader startup complete`

**Comment by qualiall** [comment]
I see the issue is a PIBCAK error.  I didn't have HookUI installed too

**Comment by 89pleasure** [comment]
Yeah if you download the mod manually from github here, please be sure you installed the requirement HookUI. Link is in the readme.
